# Generated by Django 3.2.4 on 2021-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=100, null=True)),
                ('option_one', models.CharField(max_length=100, null=True)),
                ('option_two', models.CharField(max_length=100, null=True)),
                ('option_three', models.CharField(max_length=100, null=True)),
                ('option_four', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
